spring.datasource.url=jdbc:mysql://localhost:3306/padhu32
spring.datasource.username=root
spring.datasource.password=padhu@32

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080